"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Building2, CheckCircle2, GitBranch, Layers3, LockKeyhole } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { BWPClientCase, getStoredDataAsync, INITIAL_CLIENT_CASES } from "@/lib/data";

function CaseStudy({item,index}:{item:BWPClientCase;index:number}){
  const reduced=useReducedMotion();
  return <motion.article initial={reduced?false:{opacity:0,y:30}} whileInView={reduced?undefined:{opacity:1,y:0}} viewport={{once:true,amount:.15}} className="grid lg:grid-cols-12 border-t border-slate-300 py-12 lg:py-16 gap-9">
    <div className="lg:col-span-4">
      <div className="flex items-center gap-4"><div className="w-24 h-24 bg-white border border-slate-200 p-2 flex items-center justify-center overflow-hidden">
        {item.logoDataUrl||item.coverImage?<Image src={item.logoDataUrl||item.coverImage!} alt={`Identidad de ${item.companyName}`} width={160} height={160} unoptimized className="w-full h-full object-contain"/>:<span className={`w-full h-full ${item.logoBgColor} text-white grid place-items-center font-black text-xl`}>{item.logoLetter}</span>}
      </div><div><span className="text-[10px] font-mono text-red-700">CASO / 0{index+1}</span><h2 className="text-2xl font-bold text-slate-950 mt-1">{item.companyName}</h2><p className="text-xs text-slate-500 mt-1">{item.industry}</p></div></div>
      <div className="mt-8"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-slate-400">Integraciones y plataforma</p><div className="flex flex-wrap gap-2 mt-3">{[...(item.integrations||[]),...item.technologies].map(x=><span key={x} className="text-xs border border-slate-200 px-2.5 py-1.5 bg-white">{x}</span>)}</div></div>
    </div>
    <div className="lg:col-span-8 lg:border-l lg:border-slate-200 lg:pl-10">
      <p className="text-xs font-bold text-red-800 uppercase tracking-[.18em]">{item.projectTitle}</p><p className="text-lg text-slate-600 leading-relaxed mt-5">{item.description}</p>
      <div className="grid md:grid-cols-2 gap-7 mt-9"><div><p className="text-xs font-bold text-slate-950">El reto operativo</p><p className="text-sm text-slate-600 leading-relaxed mt-2">{item.challenge||"Comprender la operación, sus restricciones y los puntos de integración antes de construir la solución."}</p></div><div><p className="text-xs font-bold text-slate-950">La solución BWP</p><p className="text-sm text-slate-600 leading-relaxed mt-2">{item.solution||item.description}</p></div></div>
      {!!item.capabilities?.length&&<div className="grid sm:grid-cols-2 gap-x-8 gap-y-3 mt-8">{item.capabilities.map(x=><div key={x} className="flex gap-2 text-sm text-slate-700"><CheckCircle2 className="w-4 h-4 text-red-700 shrink-0 mt-0.5"/>{x}</div>)}</div>}
      <div className="mt-9 bg-slate-950 text-white p-6 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><span className="text-[10px] font-mono text-red-400">RESULTADO OPERATIVO</span><p className="text-sm text-slate-200 mt-2 max-w-2xl">{item.result}</p></div><Link href="/contacto" className="inline-flex items-center gap-2 text-sm font-bold whitespace-nowrap">Evaluar proyecto <ArrowRight className="w-4 h-4"/></Link></div>
    </div>
  </motion.article>
}

export default function CasosDeExitoPage(){
  const reduced=useReducedMotion();
  const [cases,setCases]=useState(INITIAL_CLIENT_CASES);
  useEffect(()=>{let active=true;void getStoredDataAsync("client_cases",INITIAL_CLIENT_CASES).then(items=>{if(active)setCases(items.filter(x=>x.active).sort((a,b)=>a.order-b.order))});return()=>{active=false}},[]);
  const clients=cases.filter(x=>x.caseType!=="PRIVATE_PLATFORM"); const privateSystems=cases.filter(x=>x.caseType==="PRIVATE_PLATFORM");
  return <div className="bg-[#f7f7f5] min-h-screen">
    <section className="bg-slate-950 text-white pt-24 pb-20 overflow-hidden"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-12 gap-10 items-end"><div className="lg:col-span-8"><span className="text-xs font-mono text-red-400 uppercase tracking-[.25em]">Ingeniería aplicada / operación real</span><h1 className="text-5xl lg:text-7xl font-bold tracking-[-.05em] leading-[.98] mt-5">Plataformas que conectan negocio, datos y terceros.</h1><p className="text-lg text-slate-300 max-w-3xl mt-7 leading-relaxed">Casos donde BWP convierte procesos comerciales, fiscales y operativos en software integrado, trazable y preparado para crecer. Presentamos una selección reciente; nuestra experiencia incluye más implementaciones privadas y desarrollos bajo confidencialidad.</p></div><div className="lg:col-span-4 grid grid-cols-2 gap-px bg-slate-800"><div className="bg-slate-900 p-6"><Building2 className="w-6 h-6 text-red-400"/><strong className="block text-3xl mt-5">13+</strong><span className="text-xs text-slate-500">Sistemas desarrollados</span></div><div className="bg-slate-900 p-6"><Layers3 className="w-6 h-6 text-blue-400"/><strong className="block text-3xl mt-5">Recientes</strong><span className="text-xs text-slate-500">Casos seleccionados</span></div></div></div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20"><div className="grid lg:grid-cols-12 gap-8 mb-10"><div className="lg:col-span-4"><p className="text-xs font-bold text-red-800 uppercase tracking-[.2em]">Implementaciones para clientes</p></div><div className="lg:col-span-8"><h2 className="text-3xl lg:text-5xl font-bold tracking-tight text-slate-950">De la necesidad operativa a una solución conectada</h2><p className="text-slate-600 mt-4 max-w-3xl">Cada caso explica el problema, la lógica implementada, las integraciones y el valor operativo sin exponer información confidencial.</p></div></div>{clients.map((x,i)=><CaseStudy key={x.id} item={x} index={i}/>)}</section>
    <section className="bg-white border-y border-slate-200 py-24"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-start gap-4 max-w-4xl"><LockKeyhole className="w-9 h-9 text-red-800 shrink-0"/><div><p className="text-xs font-bold text-red-800 uppercase tracking-[.2em]">Software privado por suscripción</p><h2 className="text-4xl lg:text-6xl font-bold tracking-tight mt-4">Sistemas construidos para operaciones que no caben en una plantilla.</h2><p className="text-slate-600 mt-5 text-lg">Productos BWP disponibles bajo modelos privados, SaaS o licenciamiento, adaptables por empresa, permisos, sucursales e integraciones.</p></div></div><div className="grid lg:grid-cols-2 gap-6 mt-14">{privateSystems.map((x,i)=><motion.article key={x.id} whileHover={reduced?undefined:{y:-6}} className="border border-slate-200 overflow-hidden bg-[#f8f8f6]"><div className="relative aspect-[16/9] bg-slate-900">{x.coverImage&&<Image src={x.coverImage} alt={`Interfaz de ${x.companyName}`} fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover object-top"/>}<span className="absolute left-4 top-4 bg-slate-950/90 text-white text-[10px] font-mono px-3 py-2">PLATAFORMA 0{i+1}</span></div><div className="p-7"><p className="text-[10px] text-red-800 font-bold uppercase tracking-[.2em]">{x.commercialModel}</p><h3 className="text-2xl font-bold mt-3">{x.companyName}</h3><p className="text-sm text-slate-600 mt-3 leading-relaxed">{x.description}</p><div className="flex flex-wrap gap-2 mt-5">{x.capabilities?.map(c=><span key={c} className="text-xs bg-white border border-slate-200 px-2.5 py-1.5">{c}</span>)}</div></div></motion.article>)}</div></div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20"><div className="bg-gradient-to-r from-red-950 to-blue-950 text-white p-9 lg:p-14 grid lg:grid-cols-12 gap-8 items-center"><GitBranch className="w-10 h-10 text-red-300 lg:col-span-1"/><div className="lg:col-span-8"><h2 className="text-3xl font-bold">¿Su operación también necesita conectarse con otra plataforma?</h2><p className="text-slate-300 mt-3">Diseñamos el flujo, la API, los controles, el manejo de errores y la trazabilidad de extremo a extremo.</p></div><Link href="/contacto" className="lg:col-span-3 inline-flex justify-center items-center gap-2 bg-white text-slate-950 px-5 py-3.5 font-bold">Presentar necesidad <ArrowRight className="w-4 h-4"/></Link></div></section>
  </div>;
}
