import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, Bug, GraduationCap, Headphones, RefreshCw, Settings2, Wrench } from "lucide-react";

export const metadata: Metadata = { title: "Soporte y Evolución de Software | BWP Software", description: "Acompañamiento post-implementación, mantenimiento, soporte funcional, capacitación y evolución de soluciones empresariales." };

const services = [
  { icon: Headphones, title: "Atención funcional y técnica", text: "Recepción, clasificación y seguimiento de incidentes relacionados con el uso y comportamiento de la solución." },
  { icon: Bug, title: "Mantenimiento correctivo", text: "Diagnóstico y corrección de comportamientos que afecten los flujos incluidos en el alcance mantenido." },
  { icon: RefreshCw, title: "Evolución funcional", text: "Nuevos reportes, automatizaciones, módulos o ajustes priorizados conforme cambia la operación." },
  { icon: Settings2, title: "Mantenimiento preventivo", text: "Revisión técnica planificada, dependencias, capacidad, respaldos y oportunidades de optimización." },
  { icon: GraduationCap, title: "Capacitación y adopción", text: "Sesiones para usuarios clave y refuerzo cuando se incorporan personas, funciones o procesos." },
  { icon: BookOpenCheck, title: "Conocimiento y documentación", text: "Manuales, referencias operativas y registro de cambios para reducir dependencia de conocimiento informal." }
];

export default function SoportePage(){return <main className="bg-white pb-24">
  <section className="pt-28 pb-20 bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 text-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><span className="text-xs text-red-400 font-bold uppercase tracking-[0.2em]">Continuidad y evolución</span><h1 className="text-4xl lg:text-6xl font-extrabold max-w-4xl mt-4 leading-tight">El trabajo continúa después de poner el sistema en producción</h1><p className="text-lg text-slate-300 max-w-3xl mt-6 leading-relaxed">Acompañamos la estabilización, adopción y evolución de la plataforma para que siga respondiendo a la operación real de la empresa.</p></div></section>
  <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{services.map(item=>{const Icon=item.icon;return <article key={item.title} className="border border-slate-200 rounded-2xl p-7 hover:border-red-200 hover:shadow-lg transition-all"><div className="w-12 h-12 rounded-xl bg-red-50 text-red-800 flex items-center justify-center"><Icon className="w-6 h-6"/></div><h2 className="text-xl font-bold text-slate-900 mt-6">{item.title}</h2><p className="text-sm text-slate-500 leading-relaxed mt-3">{item.text}</p></article>})}</div></section>
  <section className="bg-slate-50 border-y border-slate-200 py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-12 gap-10"><div className="lg:col-span-5"><Wrench className="w-8 h-8 text-red-800"/><h2 className="text-3xl font-bold text-slate-900 mt-5">Un esquema acordado, medible y adecuado a la criticidad</h2><p className="text-slate-600 mt-4 leading-relaxed">El canal, horario, prioridades, responsables y tiempos objetivo se definen contractualmente según el sistema y el nivel de cobertura requerido.</p></div><div className="lg:col-span-7 grid sm:grid-cols-2 gap-4">{["Clasificación por prioridad", "Responsables definidos", "Registro y trazabilidad", "Ventanas de mantenimiento", "Comunicación de cambios", "Revisión periódica del servicio"].map((x,i)=><div key={x} className="bg-white border border-slate-200 rounded-xl p-5"><span className="text-xs font-mono text-red-700">0{i+1}</span><p className="font-semibold text-slate-900 mt-2">{x}</p></div>)}</div></div></section>
  <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20"><div className="bg-slate-900 rounded-2xl text-white p-8 lg:p-12 flex flex-col lg:flex-row justify-between lg:items-center gap-6"><div><h2 className="text-3xl font-bold">Definamos la cobertura adecuada para su operación</h2><p className="text-slate-300 mt-2">Cuéntenos qué sistema utiliza, cuántos usuarios dependen de él y qué nivel de continuidad necesita.</p></div><Link href="/contacto?service=Soporte%20y%20evolución" className="inline-flex items-center justify-center gap-2 bg-red-800 px-6 py-3 rounded-lg font-bold shrink-0">Solicitar evaluación <ArrowRight className="w-4 h-4"/></Link></div></section>
</main>}
