"use client";

import Link from "next/link";
import { motion, useReducedMotion, useScroll, useTransform } from "motion/react";
import { Activity, ArrowRight, BarChart3, Boxes, CheckCircle2, CloudCog, Code2, Database, Gauge, GitBranch, Layers3, Network, RefreshCw, Route, Search, ServerCog, ShieldCheck, Workflow, type LucideIcon } from "lucide-react";
import type { EnterpriseCapability } from "@/lib/enterpriseCapabilities";

const icons: Record<string, LucideIcon> = { BarChart3, Boxes, CloudCog, Code2, Database, Gauge, GitBranch, Layers3, Network, RefreshCw, Search, ServerCog, ShieldCheck, Workflow };

const visualThemes: Record<string, { hero: string; glow: string; accent: string; section: string }> = {
  "devops-cloud": { hero:"bg-[#07111f]", glow:"bg-blue-700/20", accent:"text-blue-300", section:"bg-blue-50/40" },
  "data-engineering-bi": { hero:"bg-gradient-to-br from-slate-950 via-blue-950 to-slate-900", glow:"bg-red-800/20", accent:"text-red-300", section:"bg-slate-50" },
  "modernizacion-legacy": { hero:"bg-gradient-to-br from-slate-950 via-slate-900 to-red-950", glow:"bg-red-700/20", accent:"text-red-300", section:"bg-red-50/40" },
  "centro-integraciones": { hero:"bg-gradient-to-br from-slate-950 via-blue-950 to-slate-950", glow:"bg-blue-700/20", accent:"text-blue-300", section:"bg-blue-50/40" },
  "plataformas-saas": { hero:"bg-gradient-to-br from-slate-950 via-blue-950 to-red-950", glow:"bg-red-800/20", accent:"text-red-300", section:"bg-slate-50" },
  "alto-rendimiento": { hero:"bg-slate-950", glow:"bg-red-700/15", accent:"text-red-300", section:"bg-red-50/40" },
  "consultoria-transformacion": { hero:"bg-gradient-to-br from-slate-950 via-blue-950 to-red-950", glow:"bg-blue-500/20", accent:"text-blue-300", section:"bg-blue-50/40" },
};

function SignatureVisual({ mode, reduced }: { mode: string; reduced: boolean | null }) {
  if (mode === "devops-cloud") return <div className="relative w-full max-w-md mx-auto font-mono text-xs"><div className="absolute left-5 top-6 bottom-6 w-px bg-cyan-400/30"/>{["COMMIT","BUILD","TEST","DEPLOY","OBSERVE"].map((x,i)=><motion.div key={x} initial={reduced?false:{opacity:0,x:30}} animate={reduced?undefined:{opacity:1,x:0}} transition={{delay:.35+i*.12}} className="relative ml-10 mb-3 border border-cyan-900/70 bg-slate-950/80 rounded-xl p-4 flex items-center justify-between"><span className="absolute -left-[2.65rem] w-3 h-3 bg-cyan-400 rounded-full shadow-[0_0_18px_#22d3ee]"/><span className="text-cyan-200">{x}</span><span className="text-emerald-400">✓ PASS</span></motion.div>)}</div>;
  if (mode === "data-engineering-bi") return <div className="grid grid-cols-2 gap-3 max-w-md mx-auto"><motion.div animate={reduced?undefined:{height:[110,155,125,170]}} transition={{duration:5,repeat:Infinity}} className="col-span-2 h-36 border border-violet-400/30 rounded-2xl p-5 flex items-end gap-3 bg-white/5">{[45,75,58,92,68,84].map((h,i)=><motion.span key={i} animate={reduced?undefined:{height:[`${h}%`,`${Math.min(h+15,100)}%`,`${h}%`]}} transition={{duration:2+i*.25,repeat:Infinity}} className="flex-1 bg-gradient-to-t from-violet-600 to-cyan-300 rounded-t"/>)}</motion.div>{["$ 2.8M","+ 34.2%"].map(x=><div key={x} className="border border-white/10 bg-white/5 rounded-xl p-5 text-2xl font-bold">{x}<span className="block text-[10px] text-violet-300 mt-2 font-mono">LIVE KPI</span></div>)}</div>;
  if (mode === "modernizacion-legacy") return <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 max-w-lg mx-auto"><div className="border border-amber-900 bg-black/40 rounded-2xl p-5 font-mono text-[10px] text-amber-200 space-y-3"><span className="block text-slate-500">LEGACY / V1</span>{["MONOLITH","LOCAL DB","MANUAL JOBS","OLD UI"].map(x=><span key={x} className="block border border-amber-950 p-2">{x}</span>)}</div><motion.div animate={reduced?undefined:{x:[-4,4,-4]}} transition={{duration:2,repeat:Infinity}}><RefreshCw className="w-8 h-8 text-amber-300"/></motion.div><div className="border border-emerald-800 bg-emerald-950/40 rounded-2xl p-5 font-mono text-[10px] text-emerald-200 space-y-3"><span className="block text-emerald-400">TARGET / V2</span>{["MODULAR","API-FIRST","AUTOMATED","CLOUD READY"].map(x=><span key={x} className="block border border-emerald-900 p-2">{x}</span>)}</div></div>;
  if (mode === "centro-integraciones") return <div className="relative aspect-square max-w-md mx-auto"><motion.div animate={reduced?undefined:{rotate:360}} transition={{duration:40,repeat:Infinity,ease:"linear"}} className="absolute inset-8 rounded-full border border-dashed border-emerald-500/30"/><div className="absolute inset-0 flex items-center justify-center"><div className="w-28 h-28 rounded-3xl bg-emerald-500/10 border border-emerald-400/40 flex items-center justify-center shadow-[0_0_50px_#10b98133]"><Network className="w-12 h-12 text-emerald-300"/></div></div>{["SAP","BANK","ERP","CRM","PAY","HOTEL"].map((x,i)=>{const a=(i/6)*Math.PI*2;return <motion.div key={x} animate={reduced?undefined:{scale:[1,1.1,1]}} transition={{delay:i*.2,duration:2,repeat:Infinity}} style={{left:`calc(50% + ${Math.cos(a)*42}% - 28px)`,top:`calc(50% + ${Math.sin(a)*42}% - 28px)`}} className="absolute w-14 h-14 rounded-xl bg-slate-950 border border-emerald-800 flex items-center justify-center text-[9px] font-mono text-emerald-200">{x}</motion.div>})}</div>;
  if (mode === "plataformas-saas") return <div className="max-w-md mx-auto rounded-2xl border border-fuchsia-400/30 bg-[#0f0a24]/80 shadow-2xl overflow-hidden"><div className="h-10 border-b border-white/10 flex items-center gap-2 px-4"><i className="w-2 h-2 rounded-full bg-red-400"/><i className="w-2 h-2 rounded-full bg-amber-400"/><i className="w-2 h-2 rounded-full bg-emerald-400"/><span className="ml-auto text-[9px] font-mono text-fuchsia-300">CONTROL PLANE</span></div><div className="p-5 grid grid-cols-3 gap-3">{["TENANTS","USERS","MRR"].map((x,i)=><div key={x} className="bg-white/5 rounded-lg p-3"><span className="text-[8px] text-slate-400">{x}</span><strong className="block text-xl mt-1">{[128,2480,"↑24%"][i]}</strong></div>)}{["Enterprise / Active","Growth / Active","Starter / Trial"].map((x,i)=><motion.div key={x} initial={reduced?false:{opacity:0,x:-20}} animate={reduced?undefined:{opacity:1,x:0}} transition={{delay:.4+i*.15}} className="col-span-3 flex justify-between bg-white/5 border border-white/10 rounded-lg p-3 text-xs"><span>{x}</span><span className="text-emerald-300">●</span></motion.div>)}</div></div>;
  if (mode === "alto-rendimiento") return <div className="max-w-md mx-auto font-mono"><div className="flex items-center justify-between text-lime-300 text-xs mb-4"><span>TELEMETRY / LIVE</span><Activity className="w-4 h-4"/></div><div className="h-40 border border-lime-900 bg-lime-950/10 rounded-xl overflow-hidden relative"><svg viewBox="0 0 400 140" className="absolute inset-0 w-full h-full"><motion.path d="M0 90 L30 88 L45 30 L55 110 L70 85 L130 82 L150 55 L165 95 L190 80 L250 78 L270 20 L285 115 L300 78 L400 75" fill="none" stroke="#a3e635" strokeWidth="2" initial={reduced?false:{pathLength:0}} animate={reduced?undefined:{pathLength:1}} transition={{duration:2,repeat:Infinity}}/></svg></div><div className="grid grid-cols-3 gap-2 mt-3">{["1.8ms","24K/s","99.98%"].map((x,i)=><div key={x} className="border border-lime-900 rounded-lg p-3 text-lime-200"><strong>{x}</strong><span className="block text-[8px] text-lime-700 mt-1">{["P95","THROUGHPUT","SUCCESS"][i]}</span></div>)}</div></div>;
  return <div className="relative max-w-md mx-auto space-y-3">{["DIAGNÓSTICO","ESCENARIO OBJETIVO","PORTAFOLIO","HOJA DE RUTA"].map((x,i)=><motion.div key={x} initial={reduced?false:{opacity:0,x:i%2?30:-30}} animate={reduced?undefined:{opacity:1,x:0}} transition={{delay:.3+i*.14}} className={`border border-blue-700/40 bg-blue-950/40 rounded-xl p-4 flex items-center gap-4 ${i%2?"ml-10":"mr-10"}`}><span className="w-9 h-9 rounded-full bg-red-800 flex items-center justify-center font-mono text-xs">0{i+1}</span><span className="text-xs font-bold tracking-wider">{x}</span><Route className="w-4 h-4 text-blue-300 ml-auto"/></motion.div>)}</div>;
}

function CapabilityCanvas({ mode, items, reduced }: { mode: string; items: EnterpriseCapability["capabilities"]; reduced: boolean | null }) {
  if (mode === "devops-cloud") return <div className="relative mt-14 py-8"><div className="hidden lg:block absolute left-[8%] right-[8%] top-1/2 h-px bg-gradient-to-r from-blue-900 via-red-700 to-blue-900"/><div className="grid md:grid-cols-2 lg:grid-cols-6 gap-8 lg:gap-4">{items.map((item,i)=><motion.article key={item.title} initial={reduced?false:{opacity:0,y:i%2?42:-42}} whileInView={reduced?undefined:{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}} className={`relative ${i%2?"lg:pt-32":"lg:pb-32"}`}><span className={`hidden lg:block absolute left-1/2 -translate-x-1/2 ${i%2?"top-[3.65rem]":"bottom-[3.65rem]"} w-4 h-4 rounded-full bg-red-700 ring-8 ring-red-50 shadow-[0_0_0_1px_#991b1b]`}/><p className="text-[10px] font-mono text-blue-900">PIPELINE / 0{i+1}</p><h3 className="text-lg font-bold text-slate-950 mt-3">{item.title}</h3><p className="text-sm text-slate-600 leading-relaxed mt-2">{item.text}</p></motion.article>)}</div></div>;

  if (mode === "data-engineering-bi") return <div className="mt-14 grid lg:grid-cols-12 gap-8 items-stretch"><motion.div initial={reduced?false:{opacity:0,scale:.96}} whileInView={reduced?undefined:{opacity:1,scale:1}} viewport={{once:true}} className="lg:col-span-7 bg-slate-950 text-white rounded-[2rem] p-8 relative overflow-hidden min-h-[460px]"><div className="flex justify-between"><span className="text-xs font-mono text-blue-300">DATA CONTROL ROOM</span><span className="text-xs text-slate-500">LIVE MODEL</span></div><svg viewBox="0 0 700 280" className="w-full mt-12 overflow-visible"><defs><linearGradient id="bwpArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#b91c1c" stopOpacity=".45"/><stop offset="1" stopColor="#1e3a8a" stopOpacity="0"/></linearGradient></defs><motion.path d="M0 230 C80 210 100 120 170 150 S270 245 340 130 S460 20 520 100 S620 170 700 35 L700 280 L0 280Z" fill="url(#bwpArea)" initial={reduced?false:{opacity:0}} whileInView={reduced?undefined:{opacity:1}}/><motion.path d="M0 230 C80 210 100 120 170 150 S270 245 340 130 S460 20 520 100 S620 170 700 35" fill="none" stroke="#ef4444" strokeWidth="4" initial={reduced?false:{pathLength:0}} whileInView={reduced?undefined:{pathLength:1}} viewport={{once:true}} transition={{duration:2}}/></svg><div className="absolute bottom-8 left-8 right-8 flex justify-between text-[10px] font-mono text-slate-500"><span>RAW SOURCES</span><span>GOVERNED MODEL</span><span>EXECUTIVE KPI</span></div></motion.div><div className="lg:col-span-5 divide-y divide-slate-200 border-y border-slate-200">{items.map((item,i)=><motion.article key={item.title} initial={reduced?false:{opacity:0,x:30}} whileInView={reduced?undefined:{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.07}} className="py-5 grid grid-cols-[48px_1fr] gap-4"><span className="text-xl font-black text-red-100">0{i+1}</span><div><h3 className="font-bold text-slate-950">{item.title}</h3><p className="text-xs text-slate-600 leading-relaxed mt-1">{item.text}</p></div></motion.article>)}</div></div>;

  if (mode === "modernizacion-legacy") return <div className="mt-14 relative"><div className="grid lg:grid-cols-2 min-h-[620px] overflow-hidden rounded-[3rem_0_3rem_0] border border-slate-200"><div className="bg-slate-100 p-8 lg:p-12"><span className="text-xs font-mono text-slate-500">ESTADO ACTUAL / LEGACY</span><h3 className="text-3xl font-bold text-slate-900 mt-5">Comprender y proteger</h3><div className="mt-10 space-y-8">{items.slice(0,3).map((item,i)=><motion.div key={item.title} initial={reduced?false:{opacity:0,x:-30}} whileInView={reduced?undefined:{opacity:1,x:0}} viewport={{once:true}} className="border-l-2 border-slate-400 pl-5"><span className="text-[10px] font-mono text-slate-400">DISCOVERY 0{i+1}</span><h4 className="font-bold mt-2">{item.title}</h4><p className="text-sm text-slate-600 mt-2">{item.text}</p></motion.div>)}</div></div><div className="bg-gradient-to-br from-blue-950 to-slate-950 text-white p-8 lg:p-12"><span className="text-xs font-mono text-red-300">ARQUITECTURA OBJETIVO / MODERN</span><h3 className="text-3xl font-bold mt-5">Transformar y evolucionar</h3><div className="mt-10 space-y-8">{items.slice(3).map((item,i)=><motion.div key={item.title} initial={reduced?false:{opacity:0,x:30}} whileInView={reduced?undefined:{opacity:1,x:0}} viewport={{once:true}} className="border-l-2 border-red-700 pl-5"><span className="text-[10px] font-mono text-red-400">TARGET 0{i+4}</span><h4 className="font-bold mt-2">{item.title}</h4><p className="text-sm text-slate-300 mt-2">{item.text}</p></motion.div>)}</div></div></div><motion.div animate={reduced?undefined:{rotate:360}} transition={{duration:18,repeat:Infinity,ease:"linear"}} className="hidden lg:flex absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-24 h-24 rounded-full bg-white border-8 border-slate-100 shadow-xl items-center justify-center"><RefreshCw className="w-9 h-9 text-red-700"/></motion.div></div>;

  if (mode === "centro-integraciones") return <div className="mt-14 relative min-h-[720px] lg:min-h-[640px]"><svg className="hidden lg:block absolute inset-0 w-full h-full" viewBox="0 0 1200 620"><g stroke="#cbd5e1" strokeWidth="1.5" strokeDasharray="6 8">{[[180,120],[600,50],[1020,120],[160,500],[600,570],[1040,500]].map(([x,y],i)=><motion.line key={i} x1="600" y1="310" x2={x} y2={y} initial={reduced?false:{pathLength:0}} whileInView={reduced?undefined:{pathLength:1}} viewport={{once:true}} transition={{delay:i*.12,duration:1}}/>)}</g></svg><div className="relative lg:absolute lg:left-1/2 lg:top-1/2 lg:-translate-x-1/2 lg:-translate-y-1/2 mx-auto w-48 h-48 rounded-full bg-slate-950 text-white flex flex-col items-center justify-center text-center shadow-2xl z-10"><Network className="w-10 h-10 text-red-400"/><strong className="mt-3">BWP Integration Hub</strong><span className="text-[9px] font-mono text-slate-500 mt-2">ORCHESTRATION CORE</span></div>{items.map((item,i)=>{const positions=["lg:left-[4%] lg:top-[4%]","lg:left-[39%] lg:top-0","lg:right-[4%] lg:top-[4%]","lg:left-[2%] lg:bottom-[2%]","lg:left-[39%] lg:bottom-0","lg:right-[2%] lg:bottom-[2%]"];return <motion.article key={item.title} initial={reduced?false:{opacity:0,scale:.8}} whileInView={reduced?undefined:{opacity:1,scale:1}} viewport={{once:true}} transition={{delay:i*.1}} className={`mt-4 lg:mt-0 lg:absolute w-full lg:w-[23%] ${positions[i]} text-center px-5 py-4`}><span className="inline-flex w-10 h-10 rounded-full bg-red-50 text-red-800 items-center justify-center font-mono text-xs">0{i+1}</span><h3 className="font-bold mt-3">{item.title}</h3><p className="text-xs text-slate-600 mt-2 leading-relaxed">{item.text}</p></motion.article>})}</div>;

  if (mode === "plataformas-saas") return <div className="mt-14 rounded-[2rem] border border-slate-300 bg-slate-950 shadow-2xl overflow-hidden"><div className="h-14 border-b border-slate-800 flex items-center px-5 gap-2"><span className="w-2.5 h-2.5 rounded-full bg-red-700"/><span className="w-2.5 h-2.5 rounded-full bg-blue-800"/><span className="w-2.5 h-2.5 rounded-full bg-slate-600"/><span className="ml-5 text-[10px] font-mono text-slate-500">BWP SAAS OPERATING SYSTEM</span></div><div className="grid lg:grid-cols-[220px_1fr] min-h-[580px]"><aside className="border-r border-slate-800 p-5 text-slate-500 font-mono text-xs space-y-2">{["Overview","Tenants","Subscriptions","Identity","Billing","Analytics"].map((x,i)=><motion.div key={x} whileHover={reduced?undefined:{x:5}} className={`p-3 rounded-lg ${i===0?"bg-red-900/30 text-red-200":""}`}>{x}</motion.div>)}</aside><div className="bg-slate-50 p-6 lg:p-10"><div className="flex flex-col sm:flex-row justify-between gap-4"><div><span className="text-[10px] font-mono text-red-700">PRODUCT CONTROL PLANE</span><h3 className="text-3xl font-bold mt-2">Operación centralizada</h3></div><div className="text-sm"><strong className="text-2xl">128</strong><span className="block text-xs text-slate-500">Empresas administradas</span></div></div><div className="mt-10 divide-y divide-slate-200">{items.map((item,i)=><motion.article key={item.title} initial={reduced?false:{opacity:0,x:25}} whileInView={reduced?undefined:{opacity:1,x:0}} viewport={{once:true}} className="py-5 flex gap-5"><span className="font-mono text-red-700">0{i+1}</span><div><h4 className="font-bold">{item.title}</h4><p className="text-sm text-slate-600 mt-1">{item.text}</p></div></motion.article>)}</div></div></div></div>;

  if (mode === "alto-rendimiento") return <div className="mt-14 bg-slate-950 text-white rounded-[0_3rem_0_3rem] overflow-hidden"><div className="p-8 lg:p-12 border-b border-slate-800"><div className="flex justify-between text-[10px] font-mono text-red-400"><span>PERFORMANCE LAB / TRACE 001</span><span>CAPTURE ACTIVE</span></div><svg viewBox="0 0 1000 220" className="w-full mt-6"><motion.path d="M0 150 L90 145 L120 40 L145 190 L170 145 L340 140 L390 90 L430 165 L470 138 L650 135 L690 25 L730 195 L760 138 L1000 130" fill="none" stroke="#ef4444" strokeWidth="3" initial={reduced?false:{pathLength:0}} whileInView={reduced?undefined:{pathLength:1}} viewport={{once:true}} transition={{duration:2.4}}/></svg></div><div className="grid md:grid-cols-2 lg:grid-cols-3 divide-x divide-y divide-slate-800">{items.map((item,i)=><motion.article key={item.title} whileHover={reduced?undefined:{backgroundColor:"rgba(30,58,138,.22)"}} className="p-7 min-h-52 font-mono"><span className="text-red-500 text-xs">0{i+1} / PROFILE</span><h3 className="font-bold text-lg mt-5">{item.title}</h3><p className="text-xs text-slate-400 leading-relaxed mt-3">{item.text}</p></motion.article>)}</div></div>;

  return <div className="mt-16 relative"><div className="hidden lg:block absolute left-1/2 top-0 bottom-0 w-px bg-gradient-to-b from-red-700 via-blue-900 to-slate-300"/>{items.map((item,i)=><motion.article key={item.title} initial={reduced?false:{opacity:0,x:i%2?-50:50}} whileInView={reduced?undefined:{opacity:1,x:0}} viewport={{once:true,amount:.4}} className={`relative lg:w-[46%] mb-10 ${i%2?"lg:ml-auto":""}`}><span className={`hidden lg:block absolute top-4 ${i%2?"-left-[9.8%]":"-right-[9.8%]"} w-5 h-5 rounded-full bg-white border-4 border-red-700`}/><div className={`${i%2?"lg:text-left":"lg:text-right"}`}><span className="text-xs font-mono text-red-700">DECISION / 0{i+1}</span><h3 className="text-2xl font-bold text-slate-950 mt-3">{item.title}</h3><p className="text-sm text-slate-600 leading-relaxed mt-3">{item.text}</p></div></motion.article>)}</div>;
}

function PhaseCanvas({ mode, phases, reduced, accent }: { mode: string; phases: EnterpriseCapability["phases"]; reduced: boolean | null; accent: string }) {
  if (mode === "data-engineering-bi") return <div className="mt-12 border-t border-white/15">{phases.map((phase,i)=><motion.div key={phase.title} initial={reduced?false:{opacity:0,x:40}} whileInView={reduced?undefined:{opacity:1,x:0}} viewport={{once:true}} className="grid lg:grid-cols-[100px_280px_1fr] gap-5 py-6 border-b border-white/15 items-baseline"><span className="font-mono text-red-300">DATA.0{i+1}</span><h3 className="text-xl font-bold">{phase.title}</h3><p className="text-sm text-slate-400">{phase.text}</p></motion.div>)}</div>;
  if (mode === "modernizacion-legacy") return <div className="mt-12 max-w-4xl mx-auto space-y-4">{phases.map((phase,i)=><motion.article key={phase.title} initial={reduced?false:{opacity:0,x:i%2?-50:50}} whileInView={reduced?undefined:{opacity:1,x:0}} viewport={{once:true}} className={`${i%2?"lg:ml-28":"lg:mr-28"} flex gap-5 border-l-2 border-red-700 py-3 pl-6`}><span className="font-mono text-red-300">0{i+1}</span><div><h3 className="font-bold text-xl">{phase.title}</h3><p className="text-sm text-slate-400 mt-2">{phase.text}</p></div></motion.article>)}</div>;
  if (mode === "centro-integraciones") return <div className="mt-14 flex flex-wrap justify-center gap-0">{phases.map((phase,i)=><motion.article key={phase.title} initial={reduced?false:{scale:0,rotate:-15}} whileInView={reduced?undefined:{scale:1,rotate:0}} viewport={{once:true}} transition={{delay:i*.1}} className="w-56 h-56 rounded-full border border-blue-800 bg-slate-950/60 flex flex-col justify-center text-center p-7 -m-2 hover:z-10 hover:bg-blue-950 transition-colors"><span className="font-mono text-red-300">0{i+1}</span><h3 className="font-bold mt-3">{phase.title}</h3><p className="text-[11px] text-slate-400 mt-2">{phase.text}</p></motion.article>)}</div>;
  if (mode === "plataformas-saas") return <div className="mt-12 bg-white text-slate-950 rounded-2xl overflow-hidden"><div className="grid lg:grid-cols-5">{phases.map((phase,i)=><motion.article key={phase.title} initial={reduced?false:{opacity:0,y:25}} whileInView={reduced?undefined:{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}} className="p-6 border-b lg:border-b-0 lg:border-r border-slate-200 last:border-0"><span className="inline-flex w-9 h-9 bg-red-800 text-white items-center justify-center rounded-lg font-mono text-xs">0{i+1}</span><h3 className="font-bold mt-6">{phase.title}</h3><p className="text-xs text-slate-600 mt-3 leading-relaxed">{phase.text}</p></motion.article>)}</div></div>;
  if (mode === "alto-rendimiento") return <div className="mt-12 font-mono border border-red-900 bg-black/30"><div className="px-5 py-3 border-b border-red-900 text-[10px] text-red-400">$ bwp-performance --execute-plan</div>{phases.map((phase,i)=><motion.div key={phase.title} initial={reduced?false:{opacity:0}} whileInView={reduced?undefined:{opacity:1}} viewport={{once:true}} transition={{delay:i*.12}} className="grid md:grid-cols-[80px_240px_1fr] gap-4 px-5 py-4 border-b border-slate-800 last:border-0"><span className="text-red-400">[{String(i+1).padStart(2,"0")}]</span><strong>{phase.title}</strong><span className="text-slate-400 text-xs">{phase.text}</span></motion.div>)}</div>;
  if (mode === "consultoria-transformacion") return <div className="mt-14 grid lg:grid-cols-5 gap-8 relative"><svg className="hidden lg:block absolute left-0 right-0 top-6 w-full h-16" viewBox="0 0 1000 70"><motion.path d="M30 35 C180 -10 250 80 400 35 S650 -10 970 35" fill="none" stroke="#ef4444" strokeWidth="2" strokeDasharray="8 8" initial={reduced?false:{pathLength:0}} whileInView={reduced?undefined:{pathLength:1}} viewport={{once:true}} transition={{duration:1.8}}/></svg>{phases.map((phase,i)=><motion.article key={phase.title} initial={reduced?false:{opacity:0,y:35}} whileInView={reduced?undefined:{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}} className="relative pt-16"><span className="absolute top-0 left-0 w-12 h-12 rounded-full bg-white text-slate-950 border-4 border-red-700 flex items-center justify-center font-mono text-xs">0{i+1}</span><h3 className="font-bold text-lg">{phase.title}</h3><p className="text-xs text-slate-400 mt-3">{phase.text}</p></motion.article>)}</div>;
  return <div className="mt-12 grid md:grid-cols-5 gap-0">{phases.map((phase,i)=><motion.article key={phase.title} initial={reduced?false:{opacity:0,y:i%2?30:-30}} whileInView={reduced?undefined:{opacity:1,y:0}} viewport={{once:true}} className="relative px-5 py-8 border-t border-white/20"><span className={`font-mono ${accent}`}>0{i+1}</span><h3 className="font-bold mt-5">{phase.title}</h3><p className="text-xs text-slate-400 mt-3">{phase.text}</p>{i<phases.length-1&&<ArrowRight className="hidden md:block absolute right-[-9px] top-8 w-4 h-4 text-red-400"/>}</motion.article>)}</div>;
}

function Reveal({ children, delay = 0, className = "" }: { children: React.ReactNode; delay?: number; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 28 }} whileInView={reduced ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.18 }} transition={{ duration: .7, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>;
}

export default function EnterpriseCapabilityPage({ capability }: { capability: EnterpriseCapability }) {
  const reduced = useReducedMotion();
  const { scrollYProgress } = useScroll();
  const orbY = useTransform(scrollYProgress, [0, 1], [0, 240]);
  const theme = visualThemes[capability.slug] || visualThemes["consultoria-transformacion"];

  return <main className="bwp-corporate-palette bg-[#f8fafc] overflow-hidden" data-global-motion="off">
    <section className={`relative min-h-[720px] flex items-center text-white border-b border-slate-800 ${theme.hero}`}>
      <motion.div style={reduced ? undefined : { y: orbY }} className={`absolute -top-40 right-[-8rem] w-[34rem] h-[34rem] rounded-full blur-[100px] ${theme.glow}`} />
      <div className="absolute inset-0 overflow-hidden"><div className="absolute left-[-12%] top-[8%] w-[42rem] h-[42rem] rounded-full border border-white/5"/><div className="absolute left-[-5%] top-[18%] w-[28rem] h-[28rem] rounded-full border border-red-700/10"/><svg className="absolute inset-x-0 bottom-0 w-full h-56 opacity-30" viewBox="0 0 1440 220" preserveAspectRatio="none"><motion.path d="M0 150 C240 40 420 240 700 120 S1120 20 1440 145" fill="none" stroke="#991b1b" strokeWidth="2" initial={reduced?false:{pathLength:0}} animate={reduced?undefined:{pathLength:1}} transition={{duration:2}}/><path d="M0 185 C320 75 520 255 850 145 S1200 65 1440 180" fill="none" stroke="#1e3a8a" strokeWidth="1"/></svg></div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 relative z-10 w-full grid lg:grid-cols-12 gap-14 items-center">
        <motion.div className="lg:col-span-8" initial={reduced ? false : { opacity: 0, y: 32 }} animate={reduced ? undefined : { opacity: 1, y: 0 }} transition={{ duration: .85 }}>
          <div className={`inline-flex items-center gap-3 text-[11px] font-mono uppercase tracking-[.25em] ${theme.accent}`}><span className="w-8 h-px bg-current" />{capability.eyebrow}</div>
          <h1 className="text-4xl sm:text-5xl lg:text-7xl font-bold tracking-[-0.045em] leading-[1.02] mt-6 max-w-5xl text-balance">{capability.title}</h1>
          <p className="text-lg lg:text-xl text-slate-300 leading-relaxed max-w-3xl mt-7">{capability.summary}</p>
          <div className="flex flex-wrap gap-4 mt-9"><Link href={`/contacto?service=${encodeURIComponent(capability.shortTitle)}`} className="inline-flex items-center gap-2 bg-red-800 hover:bg-red-700 px-6 py-3.5 rounded-lg font-bold transition-colors">Solicitar análisis especializado <ArrowRight className="w-4 h-4" /></Link><Link href="/casos-de-exito" className="inline-flex items-center gap-2 border border-slate-700 hover:bg-slate-900 px-6 py-3.5 rounded-lg font-bold transition-colors">Ver experiencia aplicada</Link></div>
        </motion.div>
        <motion.div className="lg:col-span-4" initial={reduced ? false : { opacity: 0, scale: .9 }} animate={reduced ? undefined : { opacity: 1, scale: 1 }} transition={{ duration: 1, delay: .15 }}>
          <SignatureVisual mode={capability.slug} reduced={reduced} />
        </motion.div>
      </div>
    </section>

    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 grid lg:grid-cols-12 gap-12">
      <Reveal className="lg:col-span-4"><p className="text-xs font-bold text-red-800 uppercase tracking-[.2em]">Visión de servicio</p><h2 className="text-3xl lg:text-4xl font-bold tracking-tight text-slate-950 mt-4">{capability.positioningTitle}</h2><p className="text-slate-600 leading-relaxed mt-5">{capability.positioning}</p></Reveal>
      <div className="lg:col-span-8 grid sm:grid-cols-2 gap-4">{capability.principles.map((item,i)=>{const Icon=icons[item.icon]||CheckCircle2;return <Reveal key={item.title} delay={i*.07}><article className="h-full bg-white border border-slate-200 rounded-2xl p-7 hover:-translate-y-1 hover:shadow-xl hover:border-red-200 transition-all duration-300"><span className="text-[10px] font-mono text-slate-400">0{i+1}</span><Icon className="w-7 h-7 text-red-800 mt-8"/><h3 className="text-xl font-bold text-slate-950 mt-5">{item.title}</h3><p className="text-sm text-slate-600 leading-relaxed mt-3">{item.text}</p></article></Reveal>})}</div>
    </section>

    <section className="bg-white border-y border-slate-200 py-24"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><Reveal className="max-w-4xl"><p className="text-xs font-bold text-red-800 uppercase tracking-[.2em]">Alcance empresarial</p><h2 className="text-3xl lg:text-5xl font-bold text-slate-950 mt-4 tracking-tight">Capacidades que cubren el ciclo completo</h2><p className="text-slate-600 mt-4 text-lg">Desde el diagnóstico y la arquitectura hasta la operación, medición y evolución continua.</p></Reveal><CapabilityCanvas mode={capability.slug} items={capability.capabilities} reduced={reduced}/></div></section>

    <section className={`text-white py-24 relative ${theme.hero}`}><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,#ffffff0d,transparent_34%)]"/><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10"><Reveal className="max-w-3xl"><p className={`text-xs font-mono uppercase tracking-[.2em] ${theme.accent}`}>Operating model</p><h2 className="text-3xl lg:text-4xl font-bold mt-4">Ejecución gobernada de principio a fin</h2><p className="text-slate-400 leading-relaxed mt-5">Cada etapa produce decisiones y entregables verificables para mantener control técnico y ejecutivo.</p></Reveal><PhaseCanvas mode={capability.slug} phases={capability.phases} reduced={reduced} accent={theme.accent}/></div></section>

    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24"><div className="grid lg:grid-cols-2 gap-6"><Reveal><div className="bg-white border border-slate-200 rounded-2xl p-8 h-full"><p className="text-xs font-bold text-red-800 uppercase tracking-[.2em]">Entregables</p><h2 className="text-3xl font-bold text-slate-950 mt-4">Evidencia concreta del trabajo</h2><div className="grid sm:grid-cols-2 gap-4 mt-8">{capability.deliverables.map(x=><div key={x} className="flex gap-3 text-sm text-slate-700"><CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0"/>{x}</div>)}</div></div></Reveal><Reveal delay={.1}><div className="bg-red-950 text-white rounded-2xl p-8 h-full"><p className="text-xs font-bold text-red-300 uppercase tracking-[.2em]">Ecosistema conectado</p><h2 className="text-3xl font-bold mt-4">Tecnologías e integraciones</h2><div className="flex flex-wrap gap-2 mt-8">{capability.technologies.map(x=><span key={x} className="px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-sm text-red-50">{x}</span>)}</div></div></Reveal></div></section>

    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-24"><Reveal><div className="relative overflow-hidden bg-gradient-to-br from-slate-950 to-blue-950 text-white rounded-[2rem] p-8 lg:p-14"><div className="absolute -right-24 -top-24 w-80 h-80 bg-red-700/20 rounded-full blur-3xl"/><div className="relative z-10 max-w-4xl"><p className="text-xs font-mono text-red-400 uppercase tracking-[.2em]">Próximo paso</p><h2 className="text-3xl lg:text-5xl font-bold mt-4">{capability.ctaTitle}</h2><p className="text-slate-300 text-lg mt-5 max-w-3xl">{capability.ctaText}</p><Link href={`/contacto?service=${encodeURIComponent(capability.shortTitle)}`} className="inline-flex items-center gap-2 bg-white text-slate-950 px-6 py-3.5 rounded-lg font-bold mt-8">Coordinar sesión ejecutiva <ArrowRight className="w-4 h-4"/></Link></div></div></Reveal></section>
    <section className="bg-[#07110d] text-white border-y border-emerald-950 py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-12 gap-10"><Reveal className="lg:col-span-4"><ShieldCheck className="w-10 h-10 text-emerald-400"/><p className="text-xs font-mono text-emerald-400 uppercase tracking-[.2em] mt-6">Secure by design</p><h2 className="text-3xl font-bold mt-3">Seguridad y vulnerabilidades dentro del ciclo completo</h2><p className="text-sm text-slate-400 leading-relaxed mt-4">Controles ajustados al riesgo, los datos, usuarios, integraciones e infraestructura.</p><Link href="/seguridad" className="inline-flex items-center gap-2 text-emerald-300 font-bold text-sm mt-6">Ver enfoque de seguridad <ArrowRight className="w-4 h-4"/></Link></Reveal><div className="lg:col-span-8 grid sm:grid-cols-2 gap-3">{["Modelado de amenazas","Código y dependencias","Pruebas de vulnerabilidad","Identidad y privilegios","API e integraciones","Operación y respuesta"].map((x,i)=><motion.article key={x} whileHover={reduced?undefined:{x:5}} className="border border-emerald-950 bg-emerald-950/20 rounded-xl p-5"><span className="text-[10px] font-mono text-emerald-600">SEC / 0{i+1}</span><h3 className="font-bold mt-2">{x}</h3><p className="text-xs text-slate-400 mt-2">Control, validación, trazabilidad y remediación según el alcance y nivel de riesgo.</p></motion.article>)}</div></div></section>
  </main>;
}
