import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Boxes, CloudCog, Database, GitBranch, LockKeyhole, MonitorSmartphone, Network, ServerCog, Workflow } from "lucide-react";

export const metadata: Metadata = { title: "Arquitectura de Software Empresarial | BWP Software", description: "Diseño de plataformas grandes, modulares, distribuidas e integradas con sistemas externos, nube, datos y aplicaciones empresariales." };

const capabilities = [
  { icon: Boxes, title: "Diseño modular", text: "Dominios y módulos separados para ventas, inventario, compras, finanzas, logística, clientes y operación." },
  { icon: GitBranch, title: "Integración externa", text: "API, webhooks, conectores y procesos de sincronización para comunicarse con ERP, bancos, pagos y otros proveedores." },
  { icon: Database, title: "Arquitectura de datos", text: "Modelos transaccionales, históricos, migraciones, auditoría y estructuras preparadas para reportes y analítica." },
  { icon: CloudCog, title: "Despliegue flexible", text: "Arquitecturas cloud, locales o híbridas según conectividad, seguridad, sistemas existentes y estrategia operativa." },
  { icon: LockKeyhole, title: "Seguridad transversal", text: "Identidad, permisos, segregación, trazabilidad y controles incorporados desde el diseño de cada flujo." },
  { icon: ServerCog, title: "Operación sostenible", text: "Ambientes, configuración, observabilidad, respaldos y documentación para facilitar mantenimiento y evolución." }
];

const flow = ["Canales y usuarios", "Servicios de negocio", "Integración y automatización", "Datos y analítica", "Infraestructura y operación"];

export default function ArquitecturaPage(){return <main className="bg-white pb-24">
  <section className="bg-slate-950 text-white pt-28 pb-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><span className="text-xs font-mono text-red-400 uppercase tracking-[0.25em]">Enterprise architecture</span><h1 className="text-4xl lg:text-6xl font-extrabold max-w-5xl mt-4 leading-tight">Plataformas grandes que conectan procesos, datos y sistemas externos</h1><p className="text-lg text-slate-300 max-w-3xl mt-6 leading-relaxed">Diseñamos soluciones como ecosistemas empresariales completos: múltiples aplicaciones, servicios, bases de datos, integraciones y controles trabajando de forma coordinada.</p></div></section>
  <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20"><div className="max-w-3xl mb-10"><span className="text-xs font-bold text-red-700 uppercase tracking-widest">Capacidades de arquitectura</span><h2 className="text-3xl font-bold text-slate-900 mt-3">Pensada para complejidad, integración y crecimiento</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{capabilities.map(item=>{const Icon=item.icon;return <article key={item.title} className="border border-slate-200 rounded-2xl p-7"><Icon className="w-7 h-7 text-red-800"/><h2 className="text-xl font-bold text-slate-900 mt-5">{item.title}</h2><p className="text-sm text-slate-500 mt-3 leading-relaxed">{item.text}</p></article>})}</div></section>
  <section className="bg-slate-950 text-white py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><Network className="w-8 h-8 text-red-400"/><h2 className="text-3xl font-bold mt-5">Modelo de plataforma empresarial</h2><p className="text-slate-400 mt-3">Cada capa tiene una responsabilidad definida y contratos claros con las demás.</p></div><div className="mt-10 space-y-3">{flow.map((layer,i)=><div key={layer} className="grid grid-cols-12 items-center border border-slate-800 rounded-xl bg-slate-900 p-5"><span className="col-span-2 lg:col-span-1 text-red-400 font-mono">0{i+1}</span><span className="col-span-8 lg:col-span-10 font-semibold">{layer}</span><ArrowRight className="col-span-2 lg:col-span-1 w-5 h-5 text-slate-600 justify-self-end"/></div>)}</div></div></section>
  <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 grid lg:grid-cols-2 gap-10"><div className="border border-slate-200 rounded-2xl p-8"><Workflow className="w-8 h-8 text-red-800"/><h2 className="text-2xl font-bold text-slate-900 mt-5">Integrar sin duplicar la operación</h2><p className="text-slate-600 mt-3 leading-relaxed">Definimos qué sistema es responsable de cada dato, cómo se intercambia, qué ocurre ante errores y cómo se mantiene la trazabilidad entre plataformas.</p><Link href="/integraciones" className="inline-flex items-center gap-2 text-red-800 font-bold text-sm mt-6">Ver integraciones <ArrowRight className="w-4 h-4"/></Link></div><div className="border border-slate-200 rounded-2xl p-8"><MonitorSmartphone className="w-8 h-8 text-red-800"/><h2 className="text-2xl font-bold text-slate-900 mt-5">Una base, múltiples experiencias</h2><p className="text-slate-600 mt-3 leading-relaxed">Una misma plataforma puede servir a personal administrativo, gerencia, clientes, proveedores, vendedores, bodegas y equipos de campo mediante canales especializados.</p><Link href="/contacto?service=Arquitectura%20empresarial" className="inline-flex items-center gap-2 text-red-800 font-bold text-sm mt-6">Evaluar una plataforma <ArrowRight className="w-4 h-4"/></Link></div></section>
</main>}
