import type { Metadata } from "next";
import Link from "next/link";
import { Activity, ArrowRight, Bug, DatabaseBackup, Eye, KeyRound, LockKeyhole, PackageSearch, ScanSearch, ServerCog, ShieldCheck, UserCheck } from "lucide-react";

export const metadata: Metadata = { title: "Seguridad y Continuidad | BWP Software", description: "Controles de seguridad, trazabilidad, respaldos y continuidad considerados por BWP Software en soluciones empresariales." };

const controls = [
  { icon: UserCheck, title: "Identidad y acceso", text: "Perfiles por función, privilegio mínimo, separación de responsabilidades y control sobre acciones sensibles." },
  { icon: LockKeyhole, title: "Protección de información", text: "Diseño cuidadoso del almacenamiento, comunicación segura y tratamiento de datos según su criticidad." },
  { icon: Eye, title: "Auditoría y trazabilidad", text: "Bitácoras para conocer qué ocurrió, quién ejecutó una acción y cuándo se produjo dentro de los procesos críticos." },
  { icon: DatabaseBackup, title: "Respaldo y recuperación", text: "Estrategias de respaldo y restauración acordes con la infraestructura, volumen y tolerancia operativa del cliente." },
  { icon: ServerCog, title: "Ambientes controlados", text: "Separación de desarrollo, pruebas y producción, configuración administrada y despliegues planificados." },
  { icon: Activity, title: "Operación observable", text: "Registro de errores, seguimiento técnico y señales de salud para facilitar diagnóstico y mantenimiento." },
  { icon: ScanSearch, title: "Evaluación de vulnerabilidades", text: "Validaciones técnicas en ambientes autorizados, clasificación de hallazgos por riesgo y seguimiento de remediación." },
  { icon: PackageSearch, title: "Dependencias y componentes", text: "Identificación de librerías vulnerables, revisión de versiones y decisiones de actualización según impacto técnico." },
  { icon: Bug, title: "Pruebas de seguridad", text: "Casos orientados a autenticación, autorización, entradas, sesiones, API y flujos sensibles según el alcance del sistema." }
];

export default function SeguridadPage() {
  return <main className="bwp-corporate-palette bg-slate-50 pb-24">
    <section className="bg-slate-950 text-white pt-28 pb-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-12 items-center"><div><span className="inline-flex items-center gap-2 text-xs font-bold text-emerald-400 uppercase tracking-[0.2em]"><ShieldCheck className="w-4 h-4"/> Seguridad desde el diseño</span><h1 className="text-4xl lg:text-6xl font-extrabold mt-4 leading-tight">Protección, control y continuidad para software empresarial</h1><p className="text-lg text-slate-300 mt-6 leading-relaxed">La seguridad no es una pantalla adicional. Se incorpora en la arquitectura, permisos, datos, integraciones, despliegue y operación de la solución.</p></div><div className="border border-slate-800 bg-slate-900 rounded-2xl p-8"><p className="text-sm font-mono text-slate-500">ENFOQUE DE RIESGO</p><div className="mt-6 space-y-5">{["Usuarios y privilegios", "Datos y transacciones", "Integraciones y servicios", "Infraestructura y recuperación"].map((x,i)=><div key={x} className="flex items-center gap-4"><span className="w-9 h-9 rounded-full border border-slate-700 flex items-center justify-center text-xs font-mono text-red-400">0{i+1}</span><span className="font-semibold">{x}</span></div>)}</div></div></div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20"><div className="max-w-3xl mb-10"><span className="text-xs font-bold text-red-700 uppercase tracking-widest">Controles por capas</span><h2 className="text-3xl font-bold text-slate-900 mt-3">La protección se diseña alrededor del proceso y de la información</h2><p className="text-slate-600 mt-3">Los controles finales se definen durante el análisis técnico según riesgos, infraestructura y requerimientos de cada organización.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{controls.map(item=>{const Icon=item.icon; return <article key={item.title} className="bg-white border border-slate-200 rounded-xl p-7"><Icon className="w-7 h-7 text-red-800"/><h3 className="font-bold text-lg text-slate-900 mt-6">{item.title}</h3><p className="text-sm text-slate-500 mt-2 leading-relaxed">{item.text}</p></article>})}</div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="bg-white border border-slate-200 rounded-2xl p-8 lg:p-12 grid lg:grid-cols-2 gap-10"><div><KeyRound className="w-8 h-8 text-red-800"/><h2 className="text-3xl font-bold mt-5 text-slate-900">Seguridad definida para su contexto</h2><p className="text-slate-600 mt-4 leading-relaxed">Antes de comprometer controles, revisamos usuarios, ubicaciones, sistemas conectados, sensibilidad de datos, recuperación esperada y responsabilidades internas.</p></div><div className="flex items-center"><Link href="/contacto?service=Análisis%20de%20seguridad" className="inline-flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-lg font-bold">Conversar sobre su arquitectura <ArrowRight className="w-4 h-4"/></Link></div></div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20"><div className="bg-slate-950 text-white rounded-2xl p-8 lg:p-12"><span className="text-xs font-mono text-emerald-400 uppercase tracking-[.2em]">Vulnerability management lifecycle</span><h2 className="text-3xl lg:text-4xl font-bold mt-4 max-w-3xl">Gestión de vulnerabilidades antes y después de producción</h2><p className="text-slate-400 mt-4 max-w-3xl leading-relaxed">El enfoque combina prevención, detección, priorización, corrección y verificación. La profundidad y frecuencia se acuerdan según criticidad, exposición y responsabilidades del cliente.</p><div className="grid md:grid-cols-5 gap-3 mt-10">{["Modelar amenazas","Revisar código y dependencias","Validar vulnerabilidades","Priorizar y remediar","Verificar y monitorear"].map((x,i)=><div key={x} className="border border-slate-800 rounded-xl p-5 bg-slate-900"><span className="text-xs font-mono text-emerald-500">0{i+1}</span><p className="font-bold mt-3">{x}</p></div>)}</div><p className="text-xs text-slate-500 mt-8">Las evaluaciones se realizan únicamente sobre activos y ambientes expresamente autorizados. Ningún proceso elimina por completo el riesgo; su objetivo es reducirlo y gestionarlo de forma continua.</p></div></section>
  </main>;
}
